export enum TipoArtefato {
    CONSTRUCTO = 'CONSTRUCTO',
    MODELO = 'MODELO',
    METODO = 'METODO',
    INSTANCIACAO = 'INSTANCIACAO',
    FRAMEWORK = 'FRAMEWORK',
    SOFTWARE = 'SOFTWARE',
    ALGORITMO = 'ALGORITMO'
}

export enum StatusProjeto {
    RASCUNHO = 'RASCUNHO',
    EM_DESENVOLVIMENTO = 'EM_DESENVOLVIMENTO',
    EM_REVISAO = 'EM_REVISAO',
    APROVADO = 'APROVADO',
    PUBLICADO = 'PUBLICADO',
    ARQUIVADO = 'ARQUIVADO'
}

export enum TipoMetodo {
    ESTUDO_CASO = 'ESTUDO_CASO',
    EXPERIMENTO = 'EXPERIMENTO',
    SURVEY = 'SURVEY',
    PROTOTIPAGEM = 'PROTOTIPAGEM',
    SIMULACAO = 'SIMULACAO',
    PESQUISA_ACAO = 'PESQUISA_ACAO'
}

export enum NivelAcesso {
    PROPRIETARIO = 'PROPRIETARIO',
    EDITOR = 'EDITOR',
    COMENTARISTA = 'COMENTARISTA',
    VISUALIZADOR = 'VISUALIZADOR'
}

export enum TipoComentario {
    GERAL = 'GERAL',
    SUGESTAO = 'SUGESTAO',
    CRITICA = 'CRITICA',
    APROVACAO = 'APROVACAO',
    DUVIDA = 'DUVIDA'
}